## 디플로이먼트
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
spec:
  replicas: 3
  selector:           # deployment - pod 대응용
    matchLabels:
      app: user-app
  template:           # 여기서부터 파드 템플릿
    metadata:
      labels:
        app: user-app      # 파드의 라벨
    spec:
      containers:
      - name: user-cont
        image: minyeongpark5/com02-onlyuser:latest
        ports:
         - containerPort: 8080  
        env:
            - name: DB_URL ## 컨테이너 환경 변수명
              valueFrom:
                configMapKeyRef:
                  name: env-config ## 컨피그맵명
                  key: datasource_url ## 키 항목
            - name: DB_USERNAME ## 컨테이너 환경 변수명
              valueFrom:
                secretKeyRef:
                  name: db-credentials ## 시크릿명
                  key: datasource_username ## 키 항목
            - name: DB_PASSWORD ## 컨테이너 환경 변수명
              valueFrom:
                secretKeyRef:
                  name: db-credentials ## 시크릿명
                  key: datasource_password ## 키 항목
            - name: MAIL_USERNAME ## 컨테이너 환경 변수명
              valueFrom:
                secretKeyRef:
                  name: db-credentials ## 시크릿명
                  key: mail_username ## 키 항목
            - name: MAIL_PASSWORD ## 컨테이너 환경 변수명
              valueFrom:
                secretKeyRef:
                  name: db-credentials ## 시크릿명
                  key: mail_password ## 키 항목
