apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: test.com02cloud.kro.kr
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: hosting
                port:
                  number: 80

