apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: test.com02cloud.kro.kr
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: hello-svc
                port:
                  number: 80
          - path: "/device"
            pathType: Prefix
            backend:
              service:
                name: device-svc
                port:
                  number: 80
          - path: "/user"
            pathType: Prefix
            backend:
              service:
                name: user-svc
                port:
                  number: 80
