apiVersion: batch/v1
kind: Job
metadata:
  name: initial-subbattery
spec:
  template:
    metadata:
      name: init-subbattery
    spec:
      containers:
      - name: init-pod
        image: shinyenggwak/micro-crawl:0.0.2
        args: ["subBattery"]
      restartPolicy: OnFailure
  backoffLimit: 3
