apiVersion: batch/v1
kind: CronJob
metadata:
  name: updater-0
spec:
  schedule: "0 9 * * 3"  # 매주 수요일 아침 9시
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: micro-updater
              image: shinyenggwak/micro-updater:0.1.2
              args: ["subBattery"]
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: env-config
                      key: datasource_url
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-credentials
                      key: datasource_password
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: db-credentials
                      key: datasource_username
          restartPolicy: OnFailure
