apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updater
spec:
  schedule: "0 9 * * 3"  # 매주 수요일 아침 9시에 돌아가도록 스케줄링
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: micro-updater
              image: shinyenggwak/micro-updater:0.0.5
              args: ["subBattery"]
          restartPolicy: OnFailure
