apiVersion: batch/v1
kind: Job
metadata:
  name: initial-subbattery
spec:
  template:
    metadata:
      name: init-subbattery
    spec:
      containers:
      - name: init-pod
        image: shinyenggwak/micro-crawl:0.1.7
        args: ["subBattery"]
        env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: datasource_url
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: datasource_password
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: datasource_username
      restartPolicy: OnFailure
  backoffLimit: 3
