apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: device-app
  template:
    metadata:
      labels:
        app: device-app
    spec:
      containers:
        - name: device-cont
          image: shinyenggwak/onlydevice:0.1.7
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: datasource_url
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: datasource_password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: datasource_username